version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  install:
    commands:
      - echo "Installing python dependencies"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Training the model..."
      - python train.py
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"linear-container","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
